-- Add likes and comments tables for engagement-based algorithm

CREATE TABLE IF NOT EXISTS "public"."likes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "post_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL
);

ALTER TABLE "public"."likes" OWNER TO "postgres";

ALTER TABLE "public"."likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."likes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_post_id_user_id_key" UNIQUE ("post_id", "user_id");

ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "public"."comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "post_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content" "text" NOT NULL
);

ALTER TABLE "public"."comments" OWNER TO "postgres";

ALTER TABLE "public"."comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

-- Policies
CREATE POLICY "Public posts are viewable by everyone." ON "public"."posts" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own posts." ON "public"."posts" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));
CREATE POLICY "Users can update their own posts." ON "public"."posts" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));
CREATE POLICY "Users can delete their own posts." ON "public"."posts" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Likes are viewable by everyone." ON "public"."likes" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own likes." ON "public"."likes" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Users can delete their own likes." ON "public"."likes" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Comments are viewable by everyone." ON "public"."comments" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own comments." ON "public"."comments" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Users can update their own comments." ON "public"."comments" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Users can delete their own comments." ON "public"."comments" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

ALTER TABLE "public"."likes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."comments" ENABLE ROW LEVEL SECURITY;

-- Grants
GRANT ALL ON TABLE "public"."likes" TO "anon";
GRANT ALL ON TABLE "public"."likes" TO "authenticated";
GRANT ALL ON TABLE "public"."likes" TO "service_role";

GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."comments" TO "anon";
GRANT ALL ON TABLE "public"."comments" TO "authenticated";
GRANT ALL ON TABLE "public"."comments" TO "service_role";

GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "service_role";

-- RPC function for timeline with relevance scoring
CREATE OR REPLACE FUNCTION get_timeline(start_idx integer, end_idx integer)
RETURNS TABLE(
  id bigint,
  created_at timestamp with time zone,
  description text,
  owner_id uuid,
  content character varying[],
  username text,
  avatar_url text,
  likes_count bigint,
  comments_count bigint,
  user_has_liked boolean,  -- Add this line
  score numeric
) AS $$
BEGIN
  RETURN QUERY
  WITH temp_posts AS (
    SELECT
      p.*,
      pr.username,
      pr.avatar_url,
      COALESCE(likes_ct.count, 0) as likes_count,
      COALESCE(comments_ct.count, 0) as comments_count,
      -- Check if the current logged-in user has liked the post
      EXISTS (
        SELECT 1 FROM likes l
        WHERE l.post_id = p.id AND l.user_id = auth.uid()
      ) AS user_has_liked
    FROM
      posts p
    LEFT JOIN
      profiles pr ON p.owner_id = pr.id
    LEFT JOIN (
      SELECT post_id, COUNT(*) as count
      FROM likes
      GROUP BY post_id
    ) likes_ct ON p.id = likes_ct.post_id
    LEFT JOIN (
      SELECT post_id, COUNT(*) as count
      FROM comments
      GROUP BY post_id
    ) comments_ct ON p.id = comments_ct.post_id
    ORDER BY
      p.created_at DESC
    LIMIT 1000
  )
  SELECT
    tp.id,
    tp.created_at,
    tp.description,
    tp.owner_id,
    tp.content,
    tp.username,
    tp.avatar_url,
    tp.likes_count,
    tp.comments_count,
    tp.user_has_liked,
    (tp.likes_count + tp.comments_count * 2 + GREATEST(0, 24 - EXTRACT(EPOCH FROM (NOW() - tp.created_at))/3600)/24 * 10)::numeric as score
  FROM
    temp_posts tp
  ORDER BY
    score DESC,
    created_at DESC
  LIMIT (end_idx - start_idx + 1) OFFSET start_idx;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION get_timeline(integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_timeline(integer, integer) TO anon;