-- Add bookmarks table and extend timeline view with bookmark status

CREATE TABLE IF NOT EXISTS public.bookmarks (
    id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    post_id bigint NOT NULL,
    profile_id uuid NOT NULL
);

ALTER TABLE public.bookmarks OWNER TO postgres;

ALTER TABLE public.bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (id);

-- prevent duplicate bookmarks per user/post
ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_post_id_profile_id_key UNIQUE (post_id, profile_id);

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- RLS policies similar to likes
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can view their own bookmarks." ON public.bookmarks FOR SELECT USING (auth.uid() = profile_id);
CREATE POLICY "Users can insert their own bookmarks." ON public.bookmarks FOR INSERT WITH CHECK (auth.uid() = profile_id);
CREATE POLICY "Users can delete their own bookmarks." ON public.bookmarks FOR DELETE USING (auth.uid() = profile_id);
CREATE POLICY "Users can't update bookmarks." ON public.bookmarks FOR UPDATE USING (false) WITH CHECK (false);

-- Grants (aligned with existing style)
GRANT ALL ON TABLE public.bookmarks TO anon;
GRANT ALL ON TABLE public.bookmarks TO authenticated;
GRANT ALL ON TABLE public.bookmarks TO service_role;

GRANT ALL ON SEQUENCE public.bookmarks_id_seq TO anon;
GRANT ALL ON SEQUENCE public.bookmarks_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.bookmarks_id_seq TO service_role;

-- Extend the timeline view to include bookmarked_by_user
DROP VIEW public.timeline;
CREATE OR REPLACE VIEW public.timeline
WITH (security_invoker=on) AS
SELECT p.id,
       p.created_at,
       p.caption,
       p.owner_id,
       pr.username AS owner_username,
       pr.avatar_url AS owner_avatar_url,
       p.media_paths,
       COUNT(DISTINCT l.id) AS likes_count,
       COUNT(DISTINCT c.id) AS comments_count,
       EXISTS (
           SELECT 1 FROM public.likes l2
           WHERE l2.post_id = p.id AND l2.user_id = auth.uid()
       ) AS liked_by_user,
       EXISTS (
           SELECT 1 FROM public.bookmarks b2
           WHERE b2.post_id = p.id AND b2.profile_id = auth.uid()
       ) AS bookmarked_by_user,
       p.latitude,
       p.longitude
FROM public.posts p
LEFT JOIN public.likes l ON l.post_id = p.id
LEFT JOIN public.comments c ON c.post_id = p.id
LEFT JOIN public.profiles pr ON p.owner_id = pr.id
GROUP BY p.id, pr.username, pr.avatar_url, p.latitude, p.longitude;
